# Pandas Homework

In [3]:
import pandas as pd

df = pd.read_csv("../data/flights.csv", engine="pyarrow")

In [4]:
# 1
df['WEATHER_DELAY'].max()

1211.0

In [6]:
# 2
# df.query("ORIGIN_AIRPORT == 'LAX' and MONTH == 12 and DESTINATION_AIRPORT=='ATL'")['ARRIVAL_DELAY'].max()

# 2
q2 = (
    df['ORIGIN_AIRPORT'] == 'LAX') & \
    (df['MONTH'] == 12) & \
    (df['DESTINATION_AIRPORT'] == 'ATL'
)
df.loc[q2, 'ARRIVAL_DELAY'].max()

296.0

In [7]:
# 3
# df3 = df.query("ORIGIN_AIRPORT == 'LAX' and MONTH == 12 and DESTINATION_AIRPORT=='ATL'")
# df3.iloc[df3['ARRIVAL_DELAY'].argmax(), :]['TAIL_NUMBER']

# 3
df3 = df.loc[q2, :]
df3.loc[df3['ARRIVAL_DELAY'] == df3['ARRIVAL_DELAY'].max(), 'TAIL_NUMBER']

5812552    N138DL
Name: TAIL_NUMBER, dtype: object

In [8]:
# 4
df3['ARRIVAL_DELAY'].min()

-36.0

In [9]:
# 5
df3.loc[df3['ARRIVAL_DELAY'] == df3['ARRIVAL_DELAY'].min(), :]['TAIL_NUMBER']

5340299    N704SW
Name: TAIL_NUMBER, dtype: object

In [11]:
# 6,7,8
# df4 = df.query("ORIGIN_AIRPORT == 'HNL'")
df4 = df.loc[df['ORIGIN_AIRPORT'] == 'HNL']
(
    df4
    .iloc[df4['AIR_TIME'].argmax(), :]
    .loc[["AIR_TIME", "DESTINATION_AIRPORT", "AIRLINE"]]
)

AIR_TIME               630.0
DESTINATION_AIRPORT      JFK
AIRLINE                   HA
Name: 2978579, dtype: object

In [12]:
# 9, 10, 11, 12
apts = ('ORD', 'AUS')
# df5 = df.query("ORIGIN_AIRPORT in @apts and DESTINATION_AIRPORT in @apts")

# q9 = df['ORIGIN_AIRPORT'].isin(apts) & df['DESTINATION_AIRPORT'].isin(apts) 
q9 = (
    (df['ORIGIN_AIRPORT'] == "ORD") & (df['DESTINATION_AIRPORT'] == 'AUS') |
    (df['ORIGIN_AIRPORT'] == "AUS") & (df['DESTINATION_AIRPORT'] == 'ORD')
)
df5 = df.loc[q9, :]
df5['AIR_TIME'].min(), df5['AIR_TIME'].mean(), df5['AIR_TIME'].median(), df5['AIR_TIME'].max()

(107.0, 133.81096451319382, 132.0, 201.0)

In [13]:
# 13, 14
# df.query("ORIGIN_AIRPORT == 'YUM'")['AIRLINE'].value_counts()
df.loc[df['ORIGIN_AIRPORT'] == 'YUM', 'AIRLINE'].value_counts()

OO    1877
Name: AIRLINE, dtype: int64

In [17]:
# 13, 14
# This is even better
# df.query("ORIGIN_AIRPORT == 'YUM'")['AIRLINE'].value_counts()
df.loc[
    (df['ORIGIN_AIRPORT'] == 'YUM') & (df['CANCELLED'] == 0),
    'AIRLINE'].value_counts()

OO    1854
Name: AIRLINE, dtype: int64

In [20]:
# 15, 16
df.dropna(subset="AIR_TIME").sort_values("AIR_TIME").head(20)
# PSG	WRG

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
4630207,2015,10,16,5,AS,65,N762AS,15841,14256,1110,...,1116.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
2731846,2015,6,21,7,AS,64,N768AS,PSG,WRG,1621,...,1632.0,-13.0,0,0,,NaN,NaN,NaN,NaN,NaN
3008622,2015,7,8,3,AS,65,N795AS,WRG,PSG,1053,...,1107.0,-4.0,0,0,,NaN,NaN,NaN,NaN,NaN
4216972,2015,9,20,7,AS,65,N796AS,WRG,PSG,1110,...,1117.0,-15.0,0,0,,NaN,NaN,NaN,NaN,NaN
717451,2015,2,17,2,AS,65,N706AS,WRG,PSG,1100,...,1058.0,-27.0,0,0,,NaN,NaN,NaN,NaN,NaN
2778272,2015,6,24,3,AS,65,N762AS,WRG,PSG,1053,...,1121.0,10.0,0,0,,NaN,NaN,NaN,NaN,NaN
940745,2015,3,3,2,AS,64,N762AS,PSG,WRG,1524,...,1530.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
3517627,2015,8,7,5,AS,65,N760AS,WRG,PSG,1053,...,1117.0,4.0,0,0,,NaN,NaN,NaN,NaN,NaN
4679617,2015,10,19,1,AS,64,N764AS,14256,15841,1523,...,1527.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
369005,2015,1,25,7,AS,65,N705AS,WRG,PSG,1100,...,1058.0,-28.0,0,0,,NaN,NaN,NaN,NaN,NaN
2582114,2015,6,12,5,AS,64,N708AS,PSG,WRG,1621,...,1627.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
4645709,2015,10,17,6,AS,65,N779AS,15841,14256,1110,...,1126.0,-8.0,0,0,,NaN,NaN,NaN,NaN,NaN
1380546,2015,3,30,1,AS,64,N762AS,PSG,WRG,1530,...,1527.0,-24.0,0,0,,NaN,NaN,NaN,NaN,NaN
4107649,2015,9,13,7,AS,65,N797AS,WRG,PSG,1110,...,1118.0,-14.0,0,0,,NaN,NaN,NaN,NaN,NaN
3623480,2015,8,13,4,AS,64,N706AS,PSG,WRG,1621,...,1634.0,-10.0,0,0,,NaN,NaN,NaN,NaN,NaN
5212701,2015,11,22,7,AS,64,N763AS,PSG,WRG,1520,...,1523.0,-20.0,0,0,,NaN,NaN,NaN,NaN,NaN
4486109,2015,10,7,3,AS,65,N765AS,15841,14256,1110,...,1124.0,-10.0,0,0,,NaN,NaN,NaN,NaN,NaN
831270,2015,2,24,2,AS,64,N763AS,PSG,WRG,1524,...,1536.0,-12.0,0,0,,NaN,NaN,NaN,NaN,NaN
2332504,2015,5,28,4,AS,64,N768AS,PSG,WRG,1530,...,1609.0,16.0,0,0,,2.0,0.0,0.0,14.0,0.0
2962045,2015,7,5,7,AS,64,N764AS,PSG,WRG,1621,...,1642.0,-3.0,0,0,,NaN,NaN,NaN,NaN,NaN

In [23]:
# 15
# This does (almost) the same but is much faster
df.dropna(subset="AIR_TIME").nsmallest(20, "AIR_TIME")

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
717451,2015,2,17,2,AS,65,N706AS,WRG,PSG,1100,...,1058.0,-27.0,0,0,,NaN,NaN,NaN,NaN,NaN
940745,2015,3,3,2,AS,64,N762AS,PSG,WRG,1524,...,1530.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
2731846,2015,6,21,7,AS,64,N768AS,PSG,WRG,1621,...,1632.0,-13.0,0,0,,NaN,NaN,NaN,NaN,NaN
2778272,2015,6,24,3,AS,65,N762AS,WRG,PSG,1053,...,1121.0,10.0,0,0,,NaN,NaN,NaN,NaN,NaN
3008622,2015,7,8,3,AS,65,N795AS,WRG,PSG,1053,...,1107.0,-4.0,0,0,,NaN,NaN,NaN,NaN,NaN
4216972,2015,9,20,7,AS,65,N796AS,WRG,PSG,1110,...,1117.0,-15.0,0,0,,NaN,NaN,NaN,NaN,NaN
4630207,2015,10,16,5,AS,65,N762AS,15841,14256,1110,...,1116.0,-18.0,0,0,,NaN,NaN,NaN,NaN,NaN
99860,2015,1,7,3,AS,65,N792AS,WRG,PSG,1100,...,1106.0,-20.0,0,0,,NaN,NaN,NaN,NaN,NaN
190390,2015,1,13,2,AS,65,N767AS,WRG,PSG,1100,...,1117.0,-9.0,0,0,,NaN,NaN,NaN,NaN,NaN
369005,2015,1,25,7,AS,65,N705AS,WRG,PSG,1100,...,1058.0,-28.0,0,0,,NaN,NaN,NaN,NaN,NaN
578781,2015,2,8,7,AS,65,N769AS,WRG,PSG,1100,...,1109.0,-16.0,0,0,,NaN,NaN,NaN,NaN,NaN
781649,2015,2,21,6,AS,65,N792AS,WRG,PSG,1100,...,1058.0,-27.0,0,0,,NaN,NaN,NaN,NaN,NaN
831270,2015,2,24,2,AS,64,N763AS,PSG,WRG,1524,...,1536.0,-12.0,0,0,,NaN,NaN,NaN,NaN,NaN
847284,2015,2,25,3,AS,64,N708AS,PSG,WRG,1524,...,1532.0,-16.0,0,0,,NaN,NaN,NaN,NaN,NaN
1032686,2015,3,9,1,AS,65,N797AS,WRG,PSG,1101,...,1115.0,-6.0,0,0,,NaN,NaN,NaN,NaN,NaN
1197213,2015,3,19,4,AS,65,N708AS,WRG,PSG,1101,...,1109.0,-12.0,0,0,,NaN,NaN,NaN,NaN,NaN
1214189,2015,3,20,5,AS,65,N796AS,WRG,PSG,1101,...,1057.0,-24.0,0,0,,NaN,NaN,NaN,NaN,NaN
1261669,2015,3,23,1,AS,65,N799AS,WRG,PSG,1101,...,1109.0,-12.0,0,0,,NaN,NaN,NaN,NaN,NaN
1282748,2015,3,24,2,AS,64,N765AS,PSG,WRG,1530,...,1540.0,-11.0,0,0,,NaN,NaN,NaN,NaN,NaN
1380546,2015,3,30,1,AS,64,N762AS,PSG,WRG,1530,...,1527.0,-24.0,0,0,,NaN,NaN,NaN,NaN,NaN

In [24]:
# 16
# df.query("ORIGIN_AIRPORT != 'JFK'").dropna(subset="AIR_TIME").sort_values("AIR_TIME", ascending=False).head(20)
apts2 = ('HNL', 'EWR')
# df.query("ORIGIN_AIRPORT in @apts2 and DESTINATION_AIRPORT in @apts2")['AIR_TIME'].mean()
df.loc[df['ORIGIN_AIRPORT'].isin(apts2) & df['DESTINATION_AIRPORT'].isin(apts2), "AIR_TIME"].mean()

574.6157407407408

In [25]:
# 17
# df.query("ORIGIN_AIRPORT == 'HNL' and DESTINATION_AIRPORT == 'JFK'")['AIR_TIME'].mean()
df.loc[(df['ORIGIN_AIRPORT'] =='HNL') & (df['DESTINATION_AIRPORT'] == 'JFK'), 'AIR_TIME'].mean()

546.4490445859873

In [26]:
# 18
# df.query("ORIGIN_AIRPORT == 'JFK' and DESTINATION_AIRPORT == 'HNL'")['AIR_TIME'].mean()
df.loc[(df['ORIGIN_AIRPORT'] =='JFK') & (df['DESTINATION_AIRPORT'] == 'HNL'), 'AIR_TIME'].mean()

635.2070063694267